sudo: required
language: generic
services:
  - docker
before_install:
  - docker build -t ram/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true ram/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-west-2"
  app: "docker-react-ram"
  env: "Dockerreactram-env"
  bucket_name: "elasticbeanstalk-us-west-2-204017957620"
  bucket_path: "docker-react-ram"
  skip_cleanup: true 
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"
